### ISSUE TITLE
Sensitive SCP blocking Support Plan signup

### ISSUE THREAD

**Issue by JimToupet** [aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium#11]
Hello there,

We just deploy the CCCS Medium. 

In our Central Network account which is in the Infrastructure OU, we try to signup for business support plan but it seems the Sensitive SCP block us with the following message :

```
User: arn:aws:sts::REDACTED:assumed-role/AWSReservedSSO_AWSAdministratorAccess_Redacted/USER@ORG.COM
Action: supportplans:ListSupportPlanModifiers
On resource(s): arn:aws:supportplans:us-east-2:redacted:/v1/listSupportPlanModifiers
Context: a policy explicitly denies the action
```
As we can see, the us-east-2 is use but the Sensitive SCP (under GBL1) deny actions not in the HOME_REGION. 

`{
      "Sid": "GBL1",
      "Effect": "Deny",
      "NotAction": [
        // minimize
        "support:*",
        // minimize
      ],
      "Resource": "*",
      "Condition": {
        "StringNotEquals": {
          "aws:RequestedRegion": "${HOME_REGION}"
        },
        "ArnNotLike": {
          "aws:PrincipalARN": ["arn:${PARTITION}:iam::*:role/${ACCELERATOR_PREFIX}*", "arn:${PARTITION}:iam::*:role/${MANAGEMENT_ACCOUNT_ACCESS_ROLE}"]
        }
      }
    }`

Is it a bug or by the design ? We need to be able to open a technical case for moving a Direct Connect to this account. What is the best way to achieve this ?

**Comment by oliviergaumond** [comment]
`supportplans` IAM actions are not included in GBL1 by design as signing up to support plans should be done at organization level. If you have Enterprise Support, adding other accounts to the plan is done by AWS Premium Support through a support case. If you need to sign up to a support plan in an individual account, an administrator of your landing zone can do it using a privileged role as necessary.
